#!/bin/bash
# Run 文字遊戲(Word Game) on Linux by applying some workarounds
#
# Based on script generated by the Proton (Steam Play compatibility tool
#
# Copyright 2021 林博仁(Buo-ren, Lin) <Buo.Ren.Lin@gmail.com>
# SPDX-License-Identifier: CC-BY-SA-4.0

GODOT_VERBOSE="${GODOT_VERBOSE:-false}"
STEAM_LIBRARY_DIR="${STEAM_LIBRARY_DIR:-"${HOME}/.local/share/Steam"}"
WINEDEBUG="${WINEDEBUG:--all}"

set \
    -o errexit \
    -o nounset

steamapps_common_dir="${STEAM_LIBRARY_DIR}/steamapps/common"
word_game_installation_dir="${steamapps_common_dir}/文字遊戲"
word_game_main_executable="${word_game_installation_dir}/文字遊戲.exe"

word_game_installation_dir_safe="${steamapps_common_dir}/WordGame"
word_game_main_executable_safe="${word_game_installation_dir_safe}/WordGame.exe"

printf 'Info: Applying unsafe path workaround...\n'
ln \
    --force \
    --relative \
    --symbolic \
    --verbose \
    "${word_game_installation_dir}" \
    "${word_game_installation_dir_safe}"
ln \
    --force \
    --relative \
    --symbolic \
    --verbose \
    "${word_game_main_executable}" \
    "${word_game_main_executable_safe}"

printf 'Info: Running game with workarounded configuration...\n'

# DISABLED: Doesn't seem to effect gameplay
#cd "${word_game_installation_dir_safe}"

DEF_CMD=("${word_game_main_executable_safe}")
if test "${GODOT_VERBOSE}" == true; then
    DEF_CMD+=(--verbose)
fi

env \
    GST_PLUGIN_SYSTEM_PATH_1_0="${STEAM_LIBRARY_DIR}/steamapps/common/Proton 6.3/dist/lib64/gstreamer-1.0:${STEAM_LIBRARY_DIR}/steamapps/common/Proton 6.3/dist/lib/gstreamer-1.0" \
    LD_LIBRARY_PATH="${STEAM_LIBRARY_DIR}/steamapps/common/Proton 6.3/dist/lib64/:/media/brlin/Ubuntu/SteamLibrary/steamapps/common/Proton 6.3/dist/lib/:/usr/lib/pressure-vessel/overrides/lib/x86_64-linux-gnu/aliases:/usr/lib/pressure-vessel/overrides/lib/i386-linux-gnu/aliases" \
    MEDIACONV_AUDIO_DUMP_FILE="${STEAM_LIBRARY_DIR}/steamapps/shadercache/1109570/fozmediav1/audio.foz" \
    MEDIACONV_AUDIO_TRANSCODED_FILE="${STEAM_LIBRARY_DIR}/steamapps/shadercache/1109570/transcoded_audio.foz" \
    MEDIACONV_VIDEO_DUMP_FILE="${STEAM_LIBRARY_DIR}/steamapps/shadercache/1109570/fozmediav1/video.foz" \
    MEDIACONV_VIDEO_TRANSCODED_FILE="${STEAM_LIBRARY_DIR}/steamapps/shadercache/1109570/transcoded_video.foz" \
    PATH="${STEAM_LIBRARY_DIR}/steamapps/common/Proton 6.3/dist/bin/:/usr/bin:/bin" \
    SteamAppId="1109570" \
    SteamGameId="1109570" \
    STEAM_COMPAT_CLIENT_INSTALL_PATH="${HOME}/.local/share/Steam" \
    TERM="xterm" \
    WINEDLLOVERRIDES="steam.exe=b;dotnetfx35.exe=b;beclient.dll=b,n;beclient_x64.dll=b,n;dxvk_config=n;d3d11=n;d3d10=n;d3d10core=n;d3d10_1=n;d3d9=n;dxgi=n" \
    WINEDLLPATH="${STEAM_LIBRARY_DIR}/steamapps/common/Proton 6.3/dist/lib64/wine:/media/brlin/Ubuntu/SteamLibrary/steamapps/common/Proton 6.3/dist/lib/wine" \
    WINEESYNC="1" \
    WINEFSYNC="1" \
    WINEPREFIX="${STEAM_LIBRARY_DIR}/steamapps/compatdata/1109570/pfx/" \
    WINE_GST_REGISTRY_DIR="${STEAM_LIBRARY_DIR}/steamapps/compatdata/1109570/gstreamer-1.0/" \
    WINE_LARGE_ADDRESS_AWARE="1" \
    "${STEAM_LIBRARY_DIR}/steamapps/common/Proton 6.3/dist/bin/wine64" \
    steam.exe \
    "${@:-${DEF_CMD[@]}}"
